### ISSUE TITLE
Automatically resize map to match associated DOM node

### ISSUE THREAD

**Issue by mwoehlke-kitware** [OpenGeoscience/geojs#280]
I can't think of any instance when I would not want this, and it seems silly that every user should have to set it up manually. Please set it up for me when the map is created.

(An option may be provided to disable this if felt necessary, but the common case should be easy.)

**Comment by aashish24** [comment]
+1 :+1:

**Comment by jbeezley** [comment]
I agree we should minimize boilerplate code.  We have discussed this issue before in the past, but we didn't come to a definite conclusion.  Here are a couple of problems off the top of my head:

1.  When the map is in a fixed size element, you don't want to resize on `$(window).resize`.
2.  `$(window).resize` only fires when the browser window is resized, not when the layout changes.  In fact there is no event at all you can use to detect a size change of a node.  For dynamic layouts, the user **must** manage this manually.

That said, I would be okay with binding to `$(window).resize` by default and providing an option to disable this behavior.

**Comment by mwoehlke-kitware** [comment]
Leaflet and OpenLayers don't have this issue; maybe it is worth looking into how they solve the problem?

**Comment by jbeezley** [comment]
They do actually have the same issues with dynamic sizes.  For example [here](https://github.com/Leaflet/Leaflet/issues/2738).  Leaflet provides a method, `invalidateSize`, that tells the map to resize according to the new node size.  There is very little difference between this and setting the size explicitly as we do.

I really don't want to make the assumption that the map should be the same size as its parent node.  For GRITS, we had a dynamic layout that required the map to resize.  Because there is no event triggered after the new layout is rendered, there is no reliable way to trigger the map resize with the correct node size.  The only option we had left was to calculate the new sizes manually and ignore the current node size.  This is ugly, but better IMO than trying to detect the new layout inside a `setTimeout` loop as is suggested in the linked issue.
