### ISSUE TITLE
Explore possibility of using slimerJS for WebGL testing

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#372]

**Comment by ronichoudhury** [comment]
Also, consider using [CasperJS](http://casperjs.org/).

**Comment by jbeezley** [comment]
I would support the idea of using CasperJS for our unit testing framework, but it doesn't help us with CI integration with webgl because it isn't headless.  It won't work on Travis or most any testing infrastructure running inside a VM.  To truly solve this issue, we need to work with [headless-gl](https://github.com/stackgl/headless-gl).
