### ISSUE TITLE
Improve documentation (Tutorials, API documentation etc.)

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#448]
We have gallery which is great, but we are missing tutorials for example. @nicopresto @jbeezley @dcjohnston what you think?

**Comment by jbeezley** [comment]
There are two big things that should happen for documentation.

* Tutorials: I had started several jsbin examples (like [this one](http://jsbin.com/tikota/23/edit?js,output)) that were intended to fill that role.  We should embed jsbin examples like this with some prose in the style of the [romanesco examples](http://romanesco.readthedocs.org/en/master/examples.html) in the RTD docs.
* [API documentation](http://opengeoscience.github.io/geojs/apidocs/):  For this we need two things:
  1. Fill in missing/incomplete docstrings.  I have been doing this as I go along.  The new lines in my refactoring branch are probably half docstrings.
  2. Fix the jsdoc template to work better with our code structure.  For example, show the classes with their namespaces `geo.core.pointFeature` rather than just `pointFeature` to distinguish the derived classes.

**Comment by aashish24** [comment]
> Tutorials: I had started several jsbin examples (like this one) that were intended to fill that role. We should embed jsbin examples like this with some prose in the style of the romanesco examples in the RTD docs.

@jbeezley are you suggesting we create RTD manually (vs parsing the source code like we do right now?). 

> API documentation: For this we need two things:
> Fill in missing/incomplete docstrings. I have been doing this as I go along. The new lines in my refactoring branch are probably half docstrings.
> Fix the jsdoc template to work better with our code structure. For example, show the classes with their namespaces geo.core.pointFeature rather than just pointFeature to distinguish the derived classes.

I have slightly different view. Talking with some other folks including @danlamanna, I am thinking that we should follow D3 like API documentation which I don't think comes from the source code. Does it?

**Comment by jbeezley** [comment]
> are you suggesting we create RTD manually (vs parsing the source code like we do right now?).

We do create RTD manually.  Only the API docs come from the source.

> I have slightly different view. Talking with some other folks including @danlamanna, I am thinking that we should follow D3 like API documentation which I don't think comes from the source code. Does it?

I don't like having the API documentation in a separate place.  D3 doesn't use embedded docstrings.  IMO, that makes the source code [hard](https://github.com/mbostock/d3/blob/master/src/arrays/nest.js) [to](https://github.com/mbostock/d3/blob/master/src/selection/selection.js) [read](https://github.com/mbostock/d3/blob/master/src/arrays/map.js).  Other popular libraries use jsdoc effectively.  For example, [glmatrix](http://glmatrix.net/docs/2.2.0/index.html) uses it with a very simple custom template, [openlayers](http://openlayers.org/en/v3.10.1/apidoc/) uses jsdoc with a highly customized template.  I also recently found [documentationjs](http://documentation.js.org/) which is compatible with jsdoc style docstrings.  As it is, we have a hard enough time writing and keeping the embedded docstrings up to date.  If we move them elsewhere, it will be orders of magnitude more difficult.

**Comment by aashish24** [comment]
> We do create RTD manually. Only the API docs come from the source.

Ah, I see. I haven't looked at the doc. thanks for the update. 



> I don't like having the API documentation in a separate place. D3 doesn't use embedded docstrings. IMO, that makes the source code hard to read. Other popular libraries use jsdoc effectively. For example, glmatrix uses it with a very simple custom template, openlayers uses jsdoc with a highly customized template. I also recently found documentationjs which is compatible with jsdoc style docstrings. As it is, we have a hard enough time writing and keeping the embedded docstrings up to date. If we move them elsewhere, it will be orders of magnitude more difficult.

that's a good point. Can we not use these templates? @dcjohnston what you think?

**Comment by jbeezley** [comment]
We could base ours off of those templates, but my guess is that they are highly customized to the code they document.

**Comment by aashish24** [comment]
ah, I see. Worth investigating? In the mean time, I will add start adding some manual documentation (basic things) for RTD

**Comment by aashish24** [comment]
- [ ] API documentation - We have to document the API better (and add missing document for older code)
- [ ] Have JSDoc display the documentation better
- [ ] Add examples in RTD

**Comment by aashish24** [comment]
I think we are waiting for a example JS source file for improving the API documentation. @jbeezley any chance you can have one for us next week?

**Comment by jbeezley** [comment]
I'm working on integrating the template at https://github.com/davidshimjs/jaguarjs-jsdoc.  This is the same template that openlayers uses and provides pretty good out of the box usability with minimal changes to our current docstrings.

**Comment by aashish24** [comment]
sounds great @jbeezley looking forward to it.

**Comment by jbeezley** [comment]
As mentioned in #697, here is a list of things we should check for in each file:
- [ ] Change each class definition to include an `@alias` tag ([example](https://github.com/OpenGeoscience/geojs/blob/6035e3071e9faf1edc8670e9e5ca7c3718c02a82/src/map.js#L16-L18)).
- [ ] Tag events with the `@event` tag ([example](https://github.com/OpenGeoscience/geojs/blob/6035e3071e9faf1edc8670e9e5ca7c3718c02a82/src/event.js#L87-L90)).
- [ ] Document events fired by functions ([example](https://github.com/OpenGeoscience/geojs/blob/6035e3071e9faf1edc8670e9e5ca7c3718c02a82/src/map.js#L422)).
- [ ] Add example blocks demonstrating how the function should be called ([example](https://github.com/OpenGeoscience/geojs/blob/6035e3071e9faf1edc8670e9e5ca7c3718c02a82/src/event.js#L16-L19)).
- [ ] Where appropriate add `@typedef` tags ([example](https://github.com/OpenGeoscience/geojs/blob/c0c5a7aa044247d02226e31eb0882626cc635ec7/src/mapInteractor.js#L330-L338)).  It might also be a good idea to move these all into a single file as well.
- [ ] Fix crosslinks so they work correctly ([example](https://github.com/OpenGeoscience/geojs/blob/6035e3071e9faf1edc8670e9e5ca7c3718c02a82/src/map.js#L1509)).
- [ ] Use markdown syntax to display structured text ([example](https://github.com/OpenGeoscience/geojs/blob/6035e3071e9faf1edc8670e9e5ca7c3718c02a82/src/util/throttle.js#L25-L33)).

I think it would also be nice to remove the [immediately invoked functions](https://github.com/OpenGeoscience/geojs/blob/master/src/camera.js#L1) since they are no longer necessary for commonjs modules.

**Comment by aashish24** [comment]
this is great @jbeezley. @jbeezley @manthey how should we split?

**Comment by manthey** [comment]
When documenting events, we end up with a title like `geo.event.event:pan`, which seems peculiar.  Is there a way to have events look like `geo.event.pan`?

**Comment by manthey** [comment]
On our getter/setter routines where we return either the current value or the class instance, should the return type be `{number|this}` or `{number|geo.map}`  (using an example where the value is a number and we are in the map class)?

**Comment by jbeezley** [comment]
Events names are usually just strings and don't typically have namespaces.  For example, you would link to a `change` event as `event:change`.  To avoid displaying them like this, we would have to modify the template used to render the documentation.

As far as getters/setters, I don't have a strong opinion.  I guess `{number|this}` would be a more accurate representation of the behavior.

**Comment by manthey** [comment]
In the geojs examples, we refer to events via a namespace, e.g. `geo.event.feature.mouseover` and `geo.event.mouseclick`.  Would it be better for the documentation to show them this way?  Or resolve to the actual string, e.g. `geo_feature_mouseover` and `geo_mouseclick`?

**Comment by aashish24** [comment]
> In the geojs examples, we refer to events via a namespace, e.g. geo.event.feature.mouseover and geo.event.mouseclick. Would it be better for the documentation to show them this way

My slight preference is for this (namespace) as I think that would be more useful for the developers but i am open on it.

**Comment by aashish24** [comment]
> As far as getters/setters, I don't have a strong opinion. I guess {number|this} would be a more accurate representation of the behavior.

{number|this} sounds good to me as it is general as well.
