### ISSUE TITLE
Document a possible API for controller (such as Mouse) for interactive manipulations 

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#491]

**Comment by jbeezley** [comment]
I've spent some time looking for possible implementations.  My first inclination was to attempt to clean up the `mapInteractor` class to formalize the concept of the "interactor state".  The current code [documents](https://github.com/OpenGeoscience/geojs/blob/master/src/core/mapInteractor.js#L288-L315) what was my initial attempt at doing so.  It kind of works, but I would want to do an overhaul before adding additional complexity to it.  Annotation controls and gestures will require this state to be extensible externally in a way that it just isn't right now.

After some thought and exploration of relevant libraries that are designed to exactly this sort of thing, I'm coming to the conclusion that embedding all of this complexity in the map interactor is probably a bad idea.  Instead, I think it would be better to support these sort of interactions via an external "annotation" class similar to what is defined in [fabric](https://github.com/kangax/fabric.js/tree/master/src/brushes).  This would work by temporarily disabling the map interactor and ceding control to the annotation interactor.  That was actually one of the intents behind the [`mapInteractor.pause`](https://github.com/OpenGeoscience/geojs/blob/master/src/core/mapInteractor.js#L1193) method.

In order to avoid a huge amount of refactoring and infrastructure work that would be necessary to enable general interactivity in the feature API, I would propose an API that would be capable of generating new features via mouse gestures, but not for modifying existing features.  This is how I would make it work:

* A new method on the map class that takes some sort of annotation class as an argument.  When called the map:
  * Disables the current map interactor
  * Creates a new, temporary layer on top of the map
  * Passes a reference to the layer to the annotation class
  * Passes a callback function to the annotation class that deletes the temporary layer and re-enables the map interactor
* The annotation class
   * Binds mouse handlers to the `div` element inside the layer
   * Handles drawing whatever it wants on the top layer
   * When finished, creates native geojs features on a feature layer, and calls the map's callback method

Because so many other javascript libraries do interactive drawing (and do it well), I don't want to reinvent the wheel.  I'm looking into [fabricjs](http://fabricjs.com/) or [paperjs](http://paperjs.org/) as a reference implementation for driving the temporary annotation layer.

A broader, but related topic, is handling serializing and deserializing of features (annotations).  This is the direction I would want to head to support general interactivity of native features.  The commercial [Draw2D](http://www.draw2d.org/draw2d/) supports something like this this in it's [io module](http://draw2d.org/draw2d_touch/jsdoc_5/#!/example/io_json_basic).  @brianhelba is working on a specification for the [Large Image](https://github.com/DigitalSlideArchive/large_image) Girder plugin that we could adopt as a standard going forward.

**Comment by aashish24** [comment]
Very well put together awesome summary :+1:  @jbeezley!! lets discuss this next week Thanks!

**Comment by aashish24** [comment]
@jbeezley I am willing to close this now. I will setup a meeting next week to discuss this document.

**Comment by jbeezley** [comment]
Okay, sounds good to me.
