### ISSUE TITLE
Switch OpenStreetMap layers so pixel perfect in the center of the zoom level

### ISSUE THREAD

**Issue by jeffbaumes** [OpenGeoscience/geojs#54]
Currently seems to only be pixel perfect at the fully zoomed out threshold for a layer, so the layer is always super-sampled, which can get bad-looking just before another layer appears when zooming in. Seems a better default would be to start with a subsampled layer, move to pixel perfect, then supersample for the remaining half of the level while zooming in. There could be a parameter that adjusts where the pixel-perfect level is reached (e.g. have a 0 to 1 continuous setting where 0 = always subsample, 1 = always supersample, and the default is 0.5).

**Comment by jbeezley** [comment]
With #318 in, the image quality is much better.  Have a look at the updated examples page.  This causes the tile levels to be chosen correctly according to the viewport size.  As @aashish24 has noted in the PR, there are some artifacts due to having a non-orthographic projection.

http://opengeoscience.github.io/geojs/examples/index.html

**Comment by jbeezley** [comment]
With #421, I think we can finally close this for real.  I put up a demo [here](http://jsbin.com/podifo/3/edit?output) using the parallel projection and discrete zoom to display the tile images without any interpolation.  Note to touchpad users, the zoom interaction is overly sensitive (issue #424).
