### ISSUE TITLE
Add NetCDF reader

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/geojs#68]

**Comment by jbeezley** [comment]
Closing because this feature isn't viable.  At best, we could only support version 3 files, which are more and more rare these days.  With more experience, we are finding that anything but superficially small data needs to be served to the client in hierarchical tiles any way.  As long as it is passed through the server for processing, it might as well be converted to a standard format using libnetcdf in the process.

**Comment by aashish24** [comment]
@jbeezley +1
